"""create user model

Revision ID: 042861652101
Revises: 
Create Date: 2024-10-30 18:46:22.005660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042861652101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=15), nullable=True),
    sa.Column('pword', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
